//
// Generated file, do not edit! Created by nedtool 5.5 from CSRequest.msg.
//

#ifndef __CSREQUEST_M_H
#define __CSREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>CSRequest.msg:2</tt> by nedtool.
 * <pre>
 * packet CSRequest
 * {
 * }
 * </pre>
 */
class CSRequest : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const CSRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CSRequest&);

  public:
    CSRequest(const char *name=nullptr, short kind=0);
    CSRequest(const CSRequest& other);
    virtual ~CSRequest();
    CSRequest& operator=(const CSRequest& other);
    virtual CSRequest *dup() const override {return new CSRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CSRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CSRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CSREQUEST_M_H

