//
// Generated file, do not edit! Created by nedtool 5.5 from CSResponse.msg.
//

#ifndef __CSRESPONSE_M_H
#define __CSRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>CSResponse.msg:2</tt> by nedtool.
 * <pre>
 * packet CSResponse
 * {
 *     bool busyChannel;
 * }
 * </pre>
 */
class CSResponse : public ::omnetpp::cPacket
{
  protected:
    bool busyChannel;

  private:
    void copy(const CSResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CSResponse&);

  public:
    CSResponse(const char *name=nullptr, short kind=0);
    CSResponse(const CSResponse& other);
    virtual ~CSResponse();
    CSResponse& operator=(const CSResponse& other);
    virtual CSResponse *dup() const override {return new CSResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getBusyChannel() const;
    virtual void setBusyChannel(bool busyChannel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CSResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CSResponse& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CSRESPONSE_M_H

