//
// Generated file, do not edit! Created by nedtool 5.5 from MacMessage.msg.
//

#ifndef __MACMESSAGE_M_H
#define __MACMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>MacMessage.msg:2</tt> by nedtool.
 * <pre>
 * packet MacMessage
 * {
 * }
 * </pre>
 */
class MacMessage : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const MacMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MacMessage&);

  public:
    MacMessage(const char *name=nullptr, short kind=0);
    MacMessage(const MacMessage& other);
    virtual ~MacMessage();
    MacMessage& operator=(const MacMessage& other);
    virtual MacMessage *dup() const override {return new MacMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MacMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MacMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MACMESSAGE_M_H

