//
// Generated file, do not edit! Created by nedtool 5.5 from TransmissionRequest.msg.
//

#ifndef __TRANSMISSIONREQUEST_M_H
#define __TRANSMISSIONREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TransmissionRequest.msg:2</tt> by nedtool.
 * <pre>
 * packet TransmissionRequest
 * {
 * }
 * </pre>
 */
class TransmissionRequest : public ::omnetpp::cPacket
{
  protected:

  private:
    void copy(const TransmissionRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransmissionRequest&);

  public:
    TransmissionRequest(const char *name=nullptr, short kind=0);
    TransmissionRequest(const TransmissionRequest& other);
    virtual ~TransmissionRequest();
    TransmissionRequest& operator=(const TransmissionRequest& other);
    virtual TransmissionRequest *dup() const override {return new TransmissionRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransmissionRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransmissionRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONREQUEST_M_H

