//
// Generated file, do not edit! Created by nedtool 5.5 from TransmissionConfirm.msg.
//

#ifndef __TRANSMISSIONCONFIRM_M_H
#define __TRANSMISSIONCONFIRM_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>TransmissionConfirm.msg:2</tt> by nedtool.
 * <pre>
 * packet TransmissionConfirm
 * {
 *     int status;
 * }
 * </pre>
 */
class TransmissionConfirm : public ::omnetpp::cPacket
{
  protected:
    int status;

  private:
    void copy(const TransmissionConfirm& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TransmissionConfirm&);

  public:
    TransmissionConfirm(const char *name=nullptr, short kind=0);
    TransmissionConfirm(const TransmissionConfirm& other);
    virtual ~TransmissionConfirm();
    TransmissionConfirm& operator=(const TransmissionConfirm& other);
    virtual TransmissionConfirm *dup() const override {return new TransmissionConfirm(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getStatus() const;
    virtual void setStatus(int status);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TransmissionConfirm& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TransmissionConfirm& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TRANSMISSIONCONFIRM_M_H

